version: "3.8"

services:
  webrtc-gateway:
    image: registry.kasemsan.com/k2-gateway:1.1.2
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
networks:
  vrs_network:
    external:
      name: vrs_network
