services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GATEWAY_URL: ${VITE_GATEWAY_URL}
        VITE_CONFIG_AUTORECORD: ${VITE_CONFIG_AUTORECORD}
    ports:
      - '4173:4173'
    environment:
      NODE_ENV: production
      FRONTEND_PASSWORD: ${FRONTEND_PASSWORD}
