import { StyleSheet } from "react-native";

import { ms, mvs, s, vs } from "@/lib/scale";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  controlsWrapper: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
  },
  chatOverlayWrapper: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 35,
  },
  locationBar: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 40,
    backgroundColor: "#26495c",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  locationIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  locationText: {
    flex: 1,
    fontSize: 12,
    color: "#fff",
  },
  chatFontBar: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 40,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignItems: "flex-end",
    // backgroundColor: "rgba(38, 73, 92, 0.85)",
  },
  chatFontControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: s(12),
  },
  chatFontButton: {
    width: s(34),
    height: s(34),
    // borderRadius: s(17),
    // borderWidth: 1,
    // borderColor: "rgba(255,255,255,0.85)",
    // backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  chatFontButtonDisabled: {
    opacity: 0.45,
  },
  chatFontButtonImage: {
    width: s(24),
    height: s(24),
  },
  chatFontButtonLabel: {
    color: "#fff",
    fontSize: ms(18),
    fontWeight: "700",
    lineHeight: ms(22),
  },
  remoteVideoContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#000",
  },
  remoteVideo: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "#000",
  },
  remoteVideoMuted: {
    flex: 1,
    backgroundColor: "#000",
    width: "100%",
    height: "100%",
  },
  localVideoContainer: {
    position: "absolute",
    top: vs(50),
    left: s(10),
    width: s(120),
    height: vs(160),
    borderRadius: s(12),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#000",
    elevation: 10,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  localVideo: {
    flex: 1,
  },
  localVideoMuted: {
    flex: 1,
    backgroundColor: "#000",
    width: "100%",
    height: "100%",
  },
  switchCameraButton: {
    position: "absolute",
    top: vs(60),
    right: s(20),
    padding: s(12),
    zIndex: 20,
  },
  contactSection: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: vs(120),
  },
  avatarText: {
    fontSize: ms(36),
    fontWeight: "bold",
    color: "#fff",
  },
  overlayInfo: {
    position: "absolute",
    top: vs(80),
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: s(20),
  },
  contactName: {
    fontSize: ms(24),
    fontWeight: "600",
    color: "#fff",
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  phoneNumber: {
    fontSize: ms(14),
    color: "rgba(255,255,255,0.8)",
    marginTop: mvs(4),
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: mvs(8),
    gap: s(8),
    backgroundColor: "#000",
    paddingHorizontal: s(16),
    paddingVertical: mvs(8),
    borderRadius: s(20),
  },
  statusDot: {
    width: s(8),
    height: s(8),
    borderRadius: s(4),
    backgroundColor: "#10B981",
  },
  duration: {
    fontSize: ms(16),
    color: "#10B981",
    fontWeight: "600",
  },
  autoRecoveryText: {
    fontSize: ms(12),
    color: "#F59E0B",
    fontWeight: "600",
  },
  reconnectingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: mvs(8),
    gap: s(8),
    backgroundColor: "rgba(245, 158, 11, 0.2)",
    paddingHorizontal: s(16),
    paddingVertical: mvs(8),
    borderRadius: s(20),
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.5)",
  },
  reconnectingDot: {
    width: s(8),
    height: s(8),
    borderRadius: s(4),
    backgroundColor: "#F59E0B",
  },
  reconnectingText: {
    fontSize: ms(16),
    color: "#F59E0B",
    fontWeight: "600",
  },
  actionsContainer: {
    position: "absolute",
    bottom: vs(120),
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: s(10),
  },
  rttContainer: {
    position: "absolute",
    left: s(16),
    right: s(16),
    bottom: vs(200),
    gap: 10,
  },
  actionButton: {
    alignItems: "center",
    justifyContent: "center",
  },
  // Removed actionRow
  // Removed actionButtonActive (replaced with iconPlaceholderActive)
  iconPlaceholder: {
    width: s(56),
    height: s(56),
    borderRadius: s(28),
    backgroundColor: "transparent",
    borderWidth: 1.5,
    borderColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
  },
  iconPlaceholderActive: {
    backgroundColor: "rgba(255, 255, 255, 0.2)",
  },
  actionLabel: {
    display: "none",
  },
  unreadBadge: {
    position: "absolute",
    top: -s(2),
    right: -s(2),
    backgroundColor: "#EF4444",
    borderRadius: s(10),
    minWidth: s(18),
    height: s(18),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: s(2),
  },
  unreadBadgeText: {
    color: "#fff",
    fontSize: ms(9),
    fontWeight: "bold",
  },
  // kickstartButton style removed
  hangupContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: vs(90),
    backgroundColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: vs(10),
  },
  hangupButtonPressed: {
    backgroundColor: "#DC2626",
  },
  // Removed old hangupButton styles as hangupContainer is now the button
  // Removed hangupLabel
  hangupIcon: {
    width: vs(56),
    height: vs(56),
  },
  switchCameraButtonImage: {
    width: vs(32),
    height: vs(32),
  },
});
