[trunk-ivr]
exten => _[2-4]000X,1,NoOp()
same => n,Dial(SIP/${EXTEN},60,rtT)

exten => 0881078400,1,NoOp()
same => n,Dial(SIP/00002,60,rtT)

exten => 322,1,NoOp(For Override)
same => n,NoOp(For Override)
same => n,Set(__USER_ID=${CALLERID(num)})
same => n,Set(__USER_UNIQUEID=${UNIQUEID})
same => n,Goto(ext-queues,322,1)


exten => 323,1,NoOp(For Override)
same => n,NoOp(For Override)
same => n,Set(__USER_ID=${CALLERID(num)})
same => n,Set(__USER_UNIQUEID=${UNIQUEID})
same => n,Goto(ext-queues,323,1)


exten => 324,1,NoOp(For Override)
same => n,NoOp(For Override)
same => n,Set(__USER_ID=${CALLERID(num)})
same => n,Set(__USER_UNIQUEID=${UNIQUEID})
same => n,Goto(ext-queues,324,1)


exten => 325,1,NoOp(For Override)
same => n,NoOp(For Override)
same => n,Set(__USER_ID=${CALLERID(num)})
same => n,Set(__USER_UNIQUEID=${UNIQUEID})
;same => n,Goto(ext-queues,325,1)
same => n,Goto(ext-queues,001,1)
