[webrtc-vrs-client]
; 1XX => W webrtc
exten => _10XXXXXXXXX,1,NoOP(_0XXXXXXXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _10XXXXXXXX,1,NoOP(_0XXXXXXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _1XXXX,1,NoOP(_XXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 1191,1,NoOP(191)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 1199,1,NoOP(199)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _114XXX,1,NoOP(14XXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 9999,1,NoOP(9999)
same => n,Goto(trunk-vrs-client,${EXTEN},1)


; 5XX => P web-public
exten => _50XXXXXXXXX,1,NoOP(_0XXXXXXXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _50XXXXXXXX,1,NoOP(_0XXXXXXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _5XXXX,1,NoOP(_XXXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 5191,1,NoOP(191)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 5199,1,NoOP(199)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => _514XXX,1,NoOP(14XXX)
same => n,Goto(trunk-vrs-client,${EXTEN},1)

exten => 9999,1,NoOP(9999)
same => n,Goto(trunk-vrs-client,${EXTEN},1)