[trunk-speech-enhancer]
exten => _X!,1,NoOp(trunk speech enhancer)
same  => n,Monitor(wav,ivr/${UNIQUEID},ob)
;same  => n,Monitor(wav,ivr/${UNIQUEID},m)
same => n,Set(CALLERID(all)=020260095)
same => n,Dial(${TRUNK_DIAL_OUT}/${EXTEN},60,rtT)