[vrs-check-service-off-receiving-sub]
; sun, mon, tue, wed, thu, fri, sat
; jan, feb, mar, apr, thu, may, jun, jul, aug, sep, oct, nov, dec 
;Receiving service time off

exten => s,1,NoOp()
same => n,Set(service_off_receiving=vrs-ext-main-service-off-receiving,${EXTEN},1)

;same => n,GotoIfTime(07:00-23:59,*,13,*?${service_off_receiving})
same => n,GotoIfTime(*,*,*,*?${service_off_receiving})
;same => n,GotoIfTime(07:01-23:59,sat,*,may?${service_off_receiving})
;same => n,GotoIfTime(*,sun,*,may?${service_off_receiving})
;same => n,GotoIfTime(00:00-07:00,mon,*,may?${service_off_receiving})
;same => n,GotoIfTime(00:00-07:00,*,1,jun?${service_off_main_repairing})

;same => n,GotoIfTime(10:00-14:00,*,22,jan?${service_off_receiving})
;same => n,GotoIfTime(23:00-07:00,*,*,*?${service_off_receiving});;Normal 07:00 -23:00
;same => n,GotoIfTime(*,*,*,*?${service_off_receiving})
;same => n,GotoIfTime(21:00-23:00,*,*,*?${service_off_receiving});;Normal 07:00 -20:00
;same => n,GotoIfTime(07:00-14:00,*,29,*?${service_off_receiving})
;same => n,GotoIfTime(*,*,3-9,oct?${service_off_receiving})
;same => n,GotoIfTime(08:10-08:25,*,*,*?${service_off_receiving})
;same => n,GotoIfTime(15:00-15:30,*,8,may?${service_off_receiving})
;same => n,GotoIfTime(00:00-22:50,*,8,jun?${service_off_receiving})
;same => n,GotoIfTime(16:00-20:00,*,21,jan?${service_off_receiving})
;same => n,GotoIfTime(18:00-23:00,thu,15,apr?${service_off_receiving})
same => n,Return()


[vrs-ext-main-service-off-receiving]
;
; Service off Receiving
;
exten => s,1,Answer
same => n,Playback(vrs-ivvr/vrs_service_off_rev)
;same => n,Playback(vrs-ivvr/timeoffservice-new)
same => n,wait(1)
same => n,HangUp