[vrs-transfer-custom]
include => ext-queues
include => ext-local
include => from-internal-additional-custom

; mcu test
exten => _0XXXXX,1,NoOp(Transfering to MCU Room)
same => n,NoOp(USER_SOURCE_TYPE=${USER_SOURCE_TYPE})
same => n,GotoIf($["${USER_SOURCE_TYPE}" = "WEB-PC"]?mcusignal:dial)
same => n(mcusignal),Gosub(send-mcusignal,s,1)
same => n(dial),Dial(SIP/${EXTEN}@mcu_out,60,rtT)
same => n,Hangup

; mcu agent
exten => _0XXXX,1,NoOp(Transfering to MCU Room)
same => n,NoOp(USER_SOURCE_TYPE=${USER_SOURCE_TYPE})
same => n,GotoIf($["${USER_SOURCE_TYPE}" = "WEB-PC"]?mcusignal:dial)
same => n(mcusignal),Gosub(send-mcusignal,s,1)
same => n(dial),Dial(SIP/${EXTEN}@mcu_out,60,rtT)
same => n,Hangup

[send-mcusignal]
exten => s,1,NoOp()
same => n,DumpChan()
same => n,Set(EXT1_FROM=MCU)
;same => n,Set(MESSAGE(to)=sip:${USER_ID}@${VRS_MOBILE_CLIENT_IP})
same => n,Set(MESSAGE(to)=sip:${USER_ID}@203.151.21.116)
;same => n,Set(MESSAGE(from)="MCU" <sip:${EXT1_FROM}@${VRS_MOBILE_CLIENT_IP}>)
same => n,Set(MESSAGE(from)="MCU" <sip:${EXT1_FROM}@203.151.21.116>)
same => n,Set(MESSAGE(body)=@MCU)
same => n,MessageSend(${MESSAGE(to)},${MESSAGE(from)})
same => n,Return()