[vrs-check-block]

; service_iqm_id description
;'*': 'ทุกบริการ'
;'1': 'SMS'
;'2': 'Message'
;'3': 'LiveChat App'
;'4': 'LiveChat Web'
;'6': 'KIOSK'
;'8': 'Caption'
;'9': 'Video Phone'
;'12': 'Web-PC'
;'15': 'TTRS Video'
;'17': 'Web-Public'

; Argument description
; ${ARG1} : SOURCE_NUMBER, exam 5000065, from ${CALLERID(num)}, ${USER_CALLERID_MAPPING}
; ${ARG2} : DESTINATION_NUMBER, exam 0971405333, from ${USER_OUT_MAPPING}, ${DIAL_EXTENSION}
; ${ARG3} : SOURCE_TYPE_IQM, exam KIOSK, from ${USER_SOURCE_TYPE}

exten => inbound,1,NoOp(VRS Check Block)
; same => n,NoOp(EXTEN_UP=${SHELL(asterisk -rx 'core show channel ${CHANNEL}')})
same => n,Set(SOURCE_NUMBER=${ARG1})
same => n,Set(DESTINATION_NUMBER=${ARG2})
same => n,Set(SOURCE_TYPE_IQM=${ARG3})
same => n,Set(BOUND_TYPE=inbound)
same => n,GotoIf($["${SOURCE_TYPE_IQM}" = "WEB-PC"]?filter99:showSourceNumber)
same => n(filter99),Set(SOURCE_NUMBER=${SOURCE_NUMBER:2})
same => n(showSourceNumber),NoOp(SOURCE_NUMBER=${SOURCE_NUMBER})
;same => n,AGI(agi://127.0.0.1/check_block,${BOUND_TYPE},${SOURCE_TYPE_IQM},${SOURCE_NUMBER},${DESTINATION_NUMBER})
same => n,AGI(${VRS_AGI_DIR}/agi_check_block.php,${BOUND_TYPE},${SOURCE_TYPE_IQM},${SOURCE_NUMBER},${DESTINATION_NUMBER})
same => n,NoOp(BLOCK=${BLOCK})
same => n,GotoIf($["${BLOCK}" = "1"]?block:noBlock)
same => n(block),NoOp(BLOCK ${CALLERID(num)})
same => n,AGI(${VRS_AGI_DIR}/agi_update_log_service.php,3,${USER_UNIQUEID},${ARG3})
same => n,Playback(beep)
same => n,wait(1)
same => n,Playback(beep)
same => n,Hangup
same => n(noBlock),Return()

exten => outbound,1,NoOp(VRS Check Block)
; same => n,NoOp(EXTEN_UP=${SHELL(asterisk -rx 'core show channel ${CHANNEL}')})
same => n,Set(SOURCE_NUMBER=${ARG1})
same => n,ExecIf($["${ARG3}" = ""]?Set(SOURCE_NUMBER=))
same => n,Set(DESTINATION_NUMBER=${ARG2})
same => n,ExecIf($["${DESTINATION_NUMBER}" = ""]?Set(DESTINATION_NUMBER=${USER_OUT_MAPPING}))
same => n,Set(SOURCE_TYPE_IQM=${ARG3})
same => n,Set(BOUND_TYPE=outbound)
same => n,GotoIf($["${SOURCE_TYPE_IQM}" = "WEB-PC"]?filter99:showSourceNumber)
same => n(filter99),Set(SOURCE_NUMBER=${SOURCE_NUMBER:2})
same => n(showSourceNumber),NoOp(SOURCE_NUMBER=${SOURCE_NUMBER})
;same => n,AGI(agi://127.0.0.1/check_block,${BOUND_TYPE},${SOURCE_TYPE_IQM},${SOURCE_NUMBER},${DESTINATION_NUMBER})
same => n,AGI(${VRS_AGI_DIR}/agi_check_block.php,${BOUND_TYPE},${SOURCE_TYPE_IQM},${SOURCE_NUMBER},${DESTINATION_NUMBER})
same => n,NoOp(BLOCK=${BLOCK})
same => n,GotoIf($["${BLOCK}" = "1"]?block:noBlock)
same => n(block),NoOp(BLOCK ${CALLERID(num)})
same => n,AGI(${VRS_AGI_DIR}/agi_update_log_dial_is_block.php)
same => n,Playback(beep)
same => n,wait(1)
same => n,Playback(beep)
same => n,Hangup
same => n(noBlock),Return()


[check-block-by-system]
exten => s,1,NoOp(Check Block)
same => n,NoOp(USER_NUMBER=${ARG1})
same => n,GotoIf($[${REGEX("^[+]66" ${ARG1})}]?re)
same => n,GotoIf($[${REGEX("^[+]" ${ARG1})}]?hangup-block,s,1)
same => n(re),Return()

[hangup-block]
exten => s,1,NoOp(Hangup Block)
same => n,NoOP(BLock Number : ${CALLERID(num)})
same => n,AGI(${VRS_AGI_DIR}/agi_block_by_system.php,${CALLERID(num)})
same => n,congestion(2)
same => n,Hangup()