[trunk-vrs-client]
; 1XX => W webrtc
; 2XX => M mobile
; 3XX => K kiosk
; 4XX => V vp
; 5XX => P web-public
; 6XX => Q mobile-public

exten => _X!,1,NoOp(${EXTEN})
same => n,NoOp(${EXTEN:1})
same => n,ExecIf($["${EXTEN:0:1}" = "1"]?Goto(W${EXTEN:1},1))
same => n,ExecIf($["${EXTEN:0:1}" = "2"]?Goto(M${EXTEN:1},1))
same => n,ExecIf($["${EXTEN:0:1}" = "3"]?Goto(K${EXTEN:1},1))
same => n,ExecIf($["${EXTEN:0:1}" = "4"]?Goto(V${EXTEN:1},1))
same => n,ExecIf($["${EXTEN:0:1}" = "5"]?Goto(P${EXTEN:1},1))
same => n,ExecIf($["${EXTEN:0:1}" = "6"]?Goto(Q${EXTEN:1},1))
same => n,Hangup()

exten => _W.,1,NoOp(WEB-PC)
same => n,NoOp(${EXTEN:1})
same => n,Set(SOURCE_TYPE=WEB-PC)
same => n,AGI(${VRS_AGI_DIR}/curl_get_webrtc_public_detail.php)
same => n,GotoIf($["${webrtc_public_name}" == ""]?:skip_web_1)
same => n,Set(CALLERID(all)="${CALLERID(num)}" <${CALLERID(num)}>)
same => n,Goto(skip_web_2)
same => n(skip_web_1),Set(CALLERID(all)="${webrtc_public_name}" <${CALLERID(num)}>)
same => n,AGI(agi://127.0.0.1/clear_same_display)
same => n(skip_web_2),Goto(vrs-client-service,${EXTEN:1},1)

exten => _M.,1,NoOp(MOBILE)
same => n,NoOp(${EXTEN:1})
same => n,Set(SOURCE_TYPE=MOBILE)
same => n,Goto(vrs-client-service,${EXTEN:1},1)

exten => _K.,1,NoOp(kiosk)
same => n,NoOp(${EXTEN:1})
same => n,Goto(vrs-user-kiosk,${EXTEN:1},1)

exten => _V.,1,NoOp(VP)
same => n,NoOp(${EXTEN:1})
same => n,NoOp(${DB(DEVICE/${EXTEN:1}/dial)})
same => n,Set(SOURCE_TYPE=VP)
same => n,GotoIf($["${DB(DEVICE/${EXTEN:1}/dial)}" != ""]?vrs-ext-local-structure,${EXTEN:1},1:vrs-client-service,${EXTEN:1},1)

exten => _P.,1,NoOp(WEB-PUBLIC)
same => n,NoOp(${EXTEN:1})
same => n,Set(NUMBER_SERVICE=${EXTEN:1})
same => n,Set(SOURCE_TYPE=WEB-PUBLIC)
; same => n,AGI(${VRS_AGI_DIR}/curl_get_webrtc_public_detail.php)
; same => n,GotoIf($["${webrtc_public_name}" == ""]?:skip_web_public_1)
; same => n,Set(CALLERID(all)="${CALLERID(num)}" <${CALLERID(num)}>)
; same => n,Goto(skip_web_public_2)
; same => n(skip_web_public_1),Set(CALLERID(all)="${webrtc_public_name}" <${CALLERID(num)}>)
; same => n,AGI(agi://127.0.0.1/clear_same_display)
; same => n(skip_web_public_2),Goto(vrs-client-service,${EXTEN:1},1)
same => n,Goto(public,1)


exten => _Q.,1,NoOp(MOBILE-PUBLIC)
same => n,NoOp(${EXTEN:1})
same => n,Set(NUMBER_SERVICE=${EXTEN:1})
same => n,Set(SOURCE_TYPE=MOBILE-PUBLIC)
; same => n,AGI(${VRS_AGI_DIR}/curl_get_webrtc_public_detail.php)
; same => n,GotoIf($["${webrtc_public_name}" == ""]?:skip_mobile_public_1)
; same => n,Set(CALLERID(all)="${CALLERID(num)}" <${CALLERID(num)}>)
; same => n,Goto(skip_mobile_public_2)
; same => n(skip_mobile_public_1),Set(CALLERID(all)="${webrtc_public_name}" <${CALLERID(num)}>)
; same => n,AGI(agi://127.0.0.1/clear_same_display)
; same => n(skip_mobile_public_2),Goto(vrs-client-service,${EXTEN:1},1)
; same => n(skip_mobile_public_2),Goto(vrs-client-service-force-table-test,${EXTEN:1},1); force test
same => n,Goto(public,1)

exten => _9999,1,Answer
same => n,Echo()
same => n,Hangup


exten => public,1,NoOp(public)
same => n,Set(CALLERID(all)="${CALLERID(num)}" <${CALLERID(num)}>)
same => n,AGI(${VRS_AGI_DIR}/curl_get_webrtc_public_detail.php)

; same => n,GotoIf($[$["${webrtc_public_name}" != ""] & $["${mobile_UID}" != ""]]?:check_name)
; same => n,Set(CALLERID(all)="${webrtc_public_name}" <${mobile_UID}>)
; same => n,Goto(clear_same_display)

;same => n(check_name),GotoIf($["${webrtc_public_name}" != ""]?:check_uid)
same => n,GotoIf($["${webrtc_public_name}" != ""]?:check_uid)
same => n,Set(CALLERID(all)="${webrtc_public_name}" <${CALLERID(num)}>)

; same => n(check_uid),GotoIf($["${mobile_UID}" != ""]?:clear_same_display)
; same => n,Set(CALLERID(all)="${CALLERID(num)}" <${mobile_UID}>)

same => n(clear_same_display),AGI(agi://127.0.0.1/clear_same_display)
same => n,Goto(vrs-client-service,${NUMBER_SERVICE},1)