TRUNK_DIAL_OUT = SIP/trunk_CAT_out
;TRUNK_DIAL_OUT = SIP/vrs_captioned
;TRUNK_DIAL_OUT = SIP/trunk_tot2_out

VRS_CLIENT_TRUNK_OUT = SIP/vrs_client_out
TRUNK_DIAL_TOT_OUT = SIP/trunk_tot2_out
TRUNK_DIAL_TOT_OUT_FAILOVER = SIP/trunk_tot1_out

;TRUNK_DIAL_TOT_OUT = SIP/trunk_CAT_out
;TRUNK_DIAL_TOT_OUT_FAILOVER = SIP/trunk_CAT_out

QUEUE_VRS_NORMAL = 810
QUEUE_VRS_EMG = 811
QUEUE_VRS_RECEIVING = 810
QUEUE_VRS_VRI = 810
QUEUE_VRS_HELPDESK = 814
QUEUE_VRS_TECHNICIAN = 815
QUEUE_VRS_INTERPRETER = 816
DEFAULTCALLERID = 020260001

VRIVATE_IP_TOT = 10.0.17.154
SERVER_IP = 203.150.245.41
AGENT_CALLER_NUM_DEFAULT = 14120
VRS_AGI_DIR = vrs_agi
PUSHKIT_DIR = vrs_agi/pushkit_for_asterisk

QUEUE_VRS_TEST = 001
QUEUE_VRI_TEST = 001
QUEUE_VRS_DEV = 009
QUEUE_VRI_DEV = 009
QUEUE_VRS_TTRS_TEST = 890

;VRS_MOBILE_CLIENT_IP = 203.151.21.116
VRS_MOBILE_CLIENT_IP = sipclient.ttrs.or.th
VRS_WEBRTC_CLIENT_IP = 203.150.245.39

TRANSFER_CONTEXT = vrs-transfer-custom

