import { ms, mvs, s, vs } from "@/lib/scale";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#111111",
  },
  remoteVideoContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#000",
  },
  remoteVideo: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "#000",
  },
  localVideoContainer: {
    position: "absolute",
    top: vs(60),
    left: s(20),
    width: s(120),
    height: vs(160),
    borderRadius: s(12),
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#000",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  localVideo: {
    flex: 1,
  },
  gradientBg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "50%",
    backgroundColor: "#1C1C1E",
    borderBottomLeftRadius: s(50),
    borderBottomRightRadius: s(50),
  },
  contactSection: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: vs(120),
  },
  avatarText: {
    fontSize: ms(36),
    fontWeight: "bold",
    color: "#fff",
  },
  overlayInfo: {
    position: "absolute",
    top: vs(80),
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: s(20),
  },
  contactName: {
    fontSize: ms(24),
    fontWeight: "600",
    color: "#fff",
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  phoneNumber: {
    fontSize: ms(14),
    color: "rgba(255,255,255,0.8)",
    marginTop: mvs(4),
  },
  statusContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: mvs(8),
    gap: s(8),
    backgroundColor: "rgba(0,0,0,0.3)",
    paddingHorizontal: s(16),
    paddingVertical: mvs(8),
    borderRadius: s(20),
  },
  statusDot: {
    width: s(8),
    height: s(8),
    borderRadius: s(4),
    backgroundColor: "#10B981",
  },
  duration: {
    fontSize: ms(16),
    color: "#10B981",
    fontWeight: "600",
  },
  connectingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: mvs(8),
    gap: s(8),
    backgroundColor: "rgba(99, 99, 102, 0.2)",
    paddingHorizontal: s(16),
    paddingVertical: mvs(8),
    borderRadius: s(20),
  },
  connectingDot: {
    width: s(8),
    height: s(8),
    borderRadius: s(4),
    backgroundColor: "#8E8E93",
  },
  connectingText: {
    fontSize: ms(16),
    color: "#8E8E93",
    fontWeight: "600",
  },
  reconnectingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: mvs(8),
    gap: s(8),
    backgroundColor: "rgba(245, 158, 11, 0.2)",
    paddingHorizontal: s(16),
    paddingVertical: mvs(8),
    borderRadius: s(20),
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.5)",
  },
  reconnectingDot: {
    width: s(8),
    height: s(8),
    borderRadius: s(4),
    backgroundColor: "#F59E0B",
  },
  reconnectingText: {
    fontSize: ms(16),
    color: "#F59E0B",
    fontWeight: "600",
  },
  rttContainer: {
    position: "absolute",
    left: s(16),
    right: s(16),
    bottom: vs(346),
  },
  actionsContainer: {
    position: "absolute",
    bottom: vs(160),
    left: 0,
    right: 0,
    paddingHorizontal: s(30),
    gap: mvs(20),
  },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  actionButton: {
    alignItems: "center",
    gap: mvs(8),
    padding: ms(12),
    borderRadius: s(16),
  },
  actionButtonActive: {
    backgroundColor: "rgba(99, 99, 102, 0.5)",
  },
  iconPlaceholder: {
    width: s(56),
    height: s(56),
    borderRadius: s(28),
    backgroundColor: "rgba(44, 44, 46, 0.8)",
    justifyContent: "center",
    alignItems: "center",
  },
  actionLabel: {
    fontSize: ms(12),
    color: "rgba(255,255,255,0.9)",
    fontWeight: "500",
  },
  unreadBadge: {
    position: "absolute",
    top: -s(4),
    right: -s(4),
    backgroundColor: "#EF4444",
    borderRadius: s(10),
    minWidth: s(20),
    height: s(20),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: s(4),
  },
  unreadBadgeText: {
    color: "#fff",
    fontSize: ms(10),
    fontWeight: "bold",
  },
  hangupContainer: {
    position: "absolute",
    bottom: vs(40),
    left: 0,
    right: 0,
    alignItems: "center",
    gap: mvs(12),
  },
  hangupButton: {
    width: s(72),
    height: s(72),
    borderRadius: s(36),
    backgroundColor: "#EF4444",
    justifyContent: "center",
    alignItems: "center",
    transform: [{ rotate: "135deg" }],
  },
  hangupButtonPressed: {
    backgroundColor: "#DC2626",
    transform: [{ rotate: "135deg" }, { scale: 0.95 }],
  },
  hangupLabel: {
    fontSize: ms(14),
    color: "#EF4444",
    fontWeight: "600",
  },
});
