/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrunksRouteImport } from './routes/trunks'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SessionDirectoryRouteImport } from './routes/session-directory'
import { Route as PublicAccountsRouteImport } from './routes/public-accounts'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ActiveSessionsRouteImport } from './routes/active-sessions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'

const TrunksRoute = TrunksRouteImport.update({
  id: '/trunks',
  path: '/trunks',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDirectoryRoute = SessionDirectoryRouteImport.update({
  id: '/session-directory',
  path: '/session-directory',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAccountsRoute = PublicAccountsRouteImport.update({
  id: '/public-accounts',
  path: '/public-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveSessionsRoute = ActiveSessionsRouteImport.update({
  id: '/active-sessions',
  path: '/active-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-sessions': typeof ActiveSessionsRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/public-accounts': typeof PublicAccountsRoute
  '/session-directory': typeof SessionDirectoryRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/trunks': typeof TrunksRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-sessions': typeof ActiveSessionsRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/public-accounts': typeof PublicAccountsRoute
  '/session-directory': typeof SessionDirectoryRoute
  '/trunks': typeof TrunksRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-sessions': typeof ActiveSessionsRoute
  '/dashboard': typeof DashboardRoute
  '/instances': typeof InstancesRoute
  '/public-accounts': typeof PublicAccountsRoute
  '/session-directory': typeof SessionDirectoryRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/trunks': typeof TrunksRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-sessions'
    | '/dashboard'
    | '/instances'
    | '/public-accounts'
    | '/session-directory'
    | '/sessions'
    | '/trunks'
    | '/sessions/$sessionId'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-sessions'
    | '/dashboard'
    | '/instances'
    | '/public-accounts'
    | '/session-directory'
    | '/trunks'
    | '/sessions/$sessionId'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/active-sessions'
    | '/dashboard'
    | '/instances'
    | '/public-accounts'
    | '/session-directory'
    | '/sessions'
    | '/trunks'
    | '/sessions/$sessionId'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveSessionsRoute: typeof ActiveSessionsRoute
  DashboardRoute: typeof DashboardRoute
  InstancesRoute: typeof InstancesRoute
  PublicAccountsRoute: typeof PublicAccountsRoute
  SessionDirectoryRoute: typeof SessionDirectoryRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  TrunksRoute: typeof TrunksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trunks': {
      id: '/trunks'
      path: '/trunks'
      fullPath: '/trunks'
      preLoaderRoute: typeof TrunksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-directory': {
      id: '/session-directory'
      path: '/session-directory'
      fullPath: '/session-directory'
      preLoaderRoute: typeof SessionDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-accounts': {
      id: '/public-accounts'
      path: '/public-accounts'
      fullPath: '/public-accounts'
      preLoaderRoute: typeof PublicAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-sessions': {
      id: '/active-sessions'
      path: '/active-sessions'
      fullPath: '/active-sessions'
      preLoaderRoute: typeof ActiveSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
  }
}

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveSessionsRoute: ActiveSessionsRoute,
  DashboardRoute: DashboardRoute,
  InstancesRoute: InstancesRoute,
  PublicAccountsRoute: PublicAccountsRoute,
  SessionDirectoryRoute: SessionDirectoryRoute,
  SessionsRoute: SessionsRouteWithChildren,
  TrunksRoute: TrunksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
